backend:
  type: "openrouter"
  model: "01-ai/yi-large"
  chat_endpoint: true

model:
  stop: [] # Remove default linebreak stop
  prefill: "Translation:" # Without this, sometimes Claude refuses to translate because of "copyright concerns" lol