backend:
  type: "openrouter"
  model: "databricks/dbrx-instruct"
  chat_endpoint: true

##model:
##  stop: [] # Remove default linebreak stop
##  prefill: "Translation:" # Without this, sometimes Claude refuses to translate because of "copyright concerns" lol