downloader:
  repo: "bartowski/Qwen2-72B-Instruct-GGUF"
  filters: "q5_k_m"
  output: ".\\gguf"
  #delete_after: true

backend:
  type: "local_openai"
  chat_endpoint: False

run:
  path: ".\\koboldcpp (6).exe"
  arguments: "--model \".\\gguf\\Qwen2-72B-Instruct-Q5_K_M.gguf\" --threads 5 --blasthreads 5 --contextsize 2048 --usecublas normal 0 --gpulayers 14 --highpriority --flashattention --nommap --multiuser 1"