backend:
  type: "lurker_proxy"
  model: "anthropic.claude-3-opus-20240229-v1:0"
  chat_endpoint: true

model:
  stop: [] # Remove default linebreak stop
  prefill: "Translation:" # Without this, sometimes Claude refuses to translate because of "copyright concerns" lol