downloader:
  repo: "bartowski/gemma-2-27b-it-GGUF"
  filters: "q5_k_m"
  output: ".\\gguf"
  #delete_after: true

backend:
  type: "local_openai"
  chat_endpoint: False

run:
  path: ".\\koboldcpp_cu12.exe"
  arguments: "--model \".\\gguf\\gemma-2-27b-it-Q5_K_M.gguf\" --threads 5 --blasthreads 5 --contextsize 2048 --usecublas mmq 0 --gpulayers 24 --highpriority --flashattention --nommap --multiuser 1 --noshift"