downloader:
  repo: "mmnga/rinna-nekomata-14b-instruction-gguf"
  filters: "q5_k_m"
  output: ".\\gguf"
  #delete_after: true

backend:
  type: "local_openai"
  chat_endpoint: False

run:
  path: ".\\koboldcpp (6).exe"
  arguments: "--model \".\\gguf\\rinna-nekomata-14b-instruction-q5_K_M.gguf\" --threads 5 --blasthreads 5 --contextsize 2048 --usecublas mmq 0 --gpulayers 38 --highpriority --flashattention --nommap --multiuser 1"